import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
import Login from '../componets/index/Login'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by Austin Liao with lucky 7" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="robots" content="index,flow" />
        <meta name="googlebot" content="index,flow" />
        <meta name="author" content="Austin Liao" />
        <title>Austin7L React App</title>
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Login />
      </main>
    </>
  )
}
